CREATE TABLE [dbo].[Klienci]
(
	[IdKlienta] int NOT NULL PRIMARY KEY IDENTITY,
	[Imie] VARCHAR(50) NOT NULL,
	[Nazwisko] VARCHAR(50) NOT NULL,
	[IdAdresu] int FOREIGN KEY REFERENCES Adres(IdAdresu) ON DELETE CASCADE ON UPDATE CASCADE,
	[Email] VARCHAR(50),
	[Telefon] VARCHAR(50) NOT NULL,
	[Pesel] VARCHAR(50) NOT NULL,
	[Nip] VARCHAR(50) DEFAULT 'BRAK',
	[NrKonta] VARCHAR(50) NOT NULL,
	[TypKlienta] BIT NOT NULL,

	)