//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestSales.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaneSamochodu
    {
        public DaneSamochodu()
        {
            this.WyposazenieDodatkowe = new HashSet<WyposazenieDodatkowe>();
            this.ZalaczoneDokumenty = new HashSet<ZalaczoneDokumenty>();
        }
    
        public int IdSamochodu { get; set; }
        public int IdMarki { get; set; }
        public string RokProdukcji { get; set; }
        public string Przebieg { get; set; }
        public string Pojemnosc { get; set; }
        public string RodzajPaliwa { get; set; }
        public string SkrzyniaBiegow { get; set; }
        public bool Bezwypadkowy { get; set; }
        public System.DateTime DataPrzegladu { get; set; }
        public System.DateTime DataUbezpieczenia { get; set; }
        public System.DateTime DataPzyjecia { get; set; }
        public string Kolor { get; set; }
        public string NrRejestracyjny { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public string Cena { get; set; }
        public string LiczbaDrzwi { get; set; }
        public string RodzajNadwozia { get; set; }
        public string KrajPochodzenia { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual MarkiSamochodow MarkiSamochodow { get; set; }
        public virtual ICollection<WyposazenieDodatkowe> WyposazenieDodatkowe { get; set; }
        public virtual ICollection<ZalaczoneDokumenty> ZalaczoneDokumenty { get; set; }
    }
}
