//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestSales.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB2KomisDataBaseEntities : DbContext
    {
        public DB2KomisDataBaseEntities()
            : base("name=DB2KomisDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<DaneSamochodu> DaneSamochodu { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<MarkiSamochodow> MarkiSamochodow { get; set; }
        public virtual DbSet<ModeleSamochodow> ModeleSamochodow { get; set; }
        public virtual DbSet<WyposazenieDodatkowe> WyposazenieDodatkowe { get; set; }
        public virtual DbSet<ZalaczoneDokumenty> ZalaczoneDokumenty { get; set; }
        public Func<object, DB2KomisDataBaseEntities, bool> CarDisplayCondtions;
    }
}
