//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestSales.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        public Klienci()
        {
            this.DaneSamochodu = new HashSet<DaneSamochodu>();
        }
    
        public int IdKlienta { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public Nullable<int> IdAdresu { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Pesel { get; set; }
        public string Nip { get; set; }
        public string NrKonta { get; set; }
        public bool TypKlienta { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual ICollection<DaneSamochodu> DaneSamochodu { get; set; }
    }
}
