//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestSales.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkiSamochodow
    {
        public MarkiSamochodow()
        {
            this.DaneSamochodu = new HashSet<DaneSamochodu>();
            this.ModeleSamochodow = new HashSet<ModeleSamochodow>();
        }
    
        public int IdMarki { get; set; }
        public string Marka { get; set; }
    
        public virtual ICollection<DaneSamochodu> DaneSamochodu { get; set; }
        public virtual ICollection<ModeleSamochodow> ModeleSamochodow { get; set; }
    }
}
