//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestSales.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZalaczoneDokumenty
    {
        public Nullable<int> IdSamochodu { get; set; }
        public string ZalaczonyDokument { get; set; }
    
        public virtual DaneSamochodu DaneSamochodu { get; set; }
    }
}
